import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
const client = readFileSync(new URL('../lib/client.js', import.meta.url), 'utf8')
const patch = readFileSync(new URL('../cordis.patch.yml', import.meta.url), 'utf8')

assert.equal(pkg.version, '0.8.0-dev.1')
assert.equal(pkg.peerDependencies['@deepseek-ai/dsh'], '0.2.0-rc.2')
assert.equal(pkg.private, true, 'development package must not publish accidentally')
assert.ok(client.includes("ctx.inject(['remote.schedule']"), 'Schedule integration must stay optional')
assert.ok(client.includes("scope.slots.inject('sidebar.panellist'"), 'attention belongs in the existing Schedule navigation seat')
assert.ok(client.includes("scope.slots.inject('sidebar.session.row.leading'"), 'scheduled Session attention must use the public Session-row leading seat')
assert.ok(client.includes("id: 'schedule-mark'"), 'enhanced Session activity must replace only the native Schedule mark occupant')
assert.ok(client.includes("scope.slots.inject('shell.overlay'"), 'delivery popup must use the Harness overlay slot')
assert.ok(client.includes("ctx.slots.inject('plugins.detail.section'"), 'notification preferences must live on the plugin detail page')
assert.ok(pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-plugin-manager'), 'Plugin Manager must be ordered before the settings contribution')
assert.ok(pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-sidebar-right'), 'native right-sidebar service must activate before quick details')
assert.ok(pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-schedule'), 'native Schedule UI must activate before the shadowed central page')
assert.ok(client.includes('hooks: { toast: toastSource, catalog }'), 'overlay must keep the authoritative Schedule catalog subscribed')
assert.ok(client.includes("className: 'sat_panelBadge'"), 'sidebar attention must expose a visible unread badge')
assert.ok(client.includes("role: 'switch'"), 'plugin notification settings must use accessible switch semantics')
assert.ok(client.includes("state.unread > 9 ? '9+'"), 'unread badge must remain compact for double-digit counts')
assert.ok(client.includes('background:var(--dsw-alias-button-ghost-active-fill);color:var(--dsw-alias-label-primary)'), 'unread badge must follow native ghost-control surface and text tokens')
assert.ok(!client.includes('background:var(--dsw-static-neutral-bluish-00);color:var(--dsw-alias-state-business-primary)'), 'badge must not hard-code the former white/blue treatment')
assert.ok(!client.includes('background:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary-foreground);font-size:8px'), 'badge must not reuse brand-primary as an accent')
assert.ok(client.includes("rightScope.slots.inject('main'"), '0.8.x quick-actions line intentionally replaces only the central Automation Tasks list')
assert.ok(client.includes("key: PANEL_ID"), 'quick-actions page must reuse the native schedules panel key')
assert.ok(client.includes("key: PANEL_ID, priority: -100"), 'quick-actions page must shadow native schedules at a distinct lower priority')
assert.ok(client.includes("rightScope.sidebarRight.openTab('scheduleTask'"), 'task details must stay on the native Schedule task tab')
assert.ok(client.includes("rightScope.remote.schedule.delete({ sessionId: record.sessionId, id: record.id })"), 'quick delete must call the native Schedule Host operation')
assert.ok(client.includes("rightScope.uiWorkspace.openSession(record.sessionId)"), 'quick open-session must use the native workspace action')
assert.ok(client.includes("taskDeleteConfirm"), 'quick delete must keep confirm-first semantics')
assert.ok(!client.includes('@deepseek-ai/dsh-client-ui-primitives'), 'plain-JS plugin must not runtime-import Harness Client internals')
assert.ok(!client.includes('document.querySelector'), 'plugin must not inspect host DOM')
assert.ok(!client.includes(':has('), 'plugin CSS must not style host DOM through parent selectors')
assert.ok(!/^\s*- id: schedule\s*$/m.test(patch), 'plugin must not own the official Schedule rows')
assert.ok(client.includes("ctx.remote.$on('schedule/changed'"), 'catalog must follow authoritative Schedule invalidation')
assert.ok(client.includes("ctx.remote.schedule.history({ sessionId: record.sessionId, id: record.id, limit: 10 })"), 'recurring unread count must use native retained delivery history with a bounded page')
assert.ok(client.includes("if (candidates.length >= 10) return historyByTask"), 'ten distinct unread tasks must skip unnecessary history reads')
assert.ok(client.includes("Math.min(4, candidates.length)"), 'delivery-history enrichment must keep bounded concurrency')
assert.ok(client.includes("if (count >= 10) break"), 'history counting must stop once the 9+ badge threshold is known')
assert.ok(client.includes("historyByTask: new Map()"), 'catalog snapshots must carry delivery-history enrichment')
assert.ok(client.includes('markCurrentDeliveriesNotified(records)'), 'first browser read must baseline popup dedupe without clearing unread')
assert.ok(client.includes("ctx.on('connection/reset'"), 'catalog must recover after reconnect')
assert.ok(client.includes("const SEEN_STORAGE_KEY = PACKAGE + '/seen-v2'"), 'legacy seen state must remain compatible')
assert.ok(client.includes("const SESSION_SEEN_STORAGE_KEY = PACKAGE + '/session-delivery-seen-v1'"), 'Session activity acknowledgement must be independent from task-center seen state')
assert.ok(client.includes('activePanelId === null && mainSessionId === sessionId'), 'Session activity must clear only when the conversation is actually visible')
assert.ok(client.includes('markSessionRecordSeen(record)'), 'Open conversation from the popup must acknowledge Session activity')
assert.ok(client.includes("const PREFERENCES_STORAGE_KEY = PACKAGE + '/notification-preferences-v1'"), 'legacy notification preferences must remain compatible')
assert.ok(client.includes('startPreferencesStorageSync'), 'browser-local preferences must synchronize across tabs')
assert.ok(client.includes('const justActivated = active && !panelWasActive'), 'attention acknowledgement must require an inactive-to-active panel transition')
assert.ok(client.includes('panelWasActive = active'), 'panel activation state must survive ordinary sidebar rerenders')
assert.ok(client.includes('markAllSeen(catalog.records)'), 'panel activation must acknowledge current attention')

console.log('DSH 0.2.0-rc.2 quick-actions contract passed')
